### ISSUE TITLE
Blender UI hangs after rendering is started

### ISSUE THREAD

**Issue by zezic** [LuxCoreRender/BlendLuxCore#385]
#### System Information

Ubuntu 18.04 with AMD Vega 56

#### Software Version

* Blender version: 2.82 (first stable release)
* LuxCore version: 2.3 beta2 as well as build from 97a03c8 (both with opencl)

#### Error message from Blender console

<details><summary>Logs:</summary><p>

```
Read prefs: /home/zezic/.config/blender/2.82/config/userpref.blend
found bundled python: /home/zezic/Documents/Soft/Graphics/blender-2.82-linux64/2.82/python
BlendLuxCore registered (2.3beta1)
Updating OpenCL device list
==================================================
[Engine/Final] Rendering layer "View Layer"
[Exporter] Creating session
[SDL][25.523] Camera type: perspective
[SDL][25.523] Camera position: Point[7.35889, -6.92579, 4.95831]
[SDL][25.523] Camera target: Point[6.70733, -6.31162, 4.51304]
[SDL][25.523] Camera clipping plane disabled
Converting: Cube
Converting: Light
[SDL][25.528] Material definition: __CLAY__
[SDL][25.529] Material definition: Material140676416138632
[SDL][25.529] Scene objects count: 1
[SDL][25.529] Light definition: 140676445176840
[SDL][25.529] Material re-definition: __CLAY__
[SDL][25.529] Material re-definition: Material140676416138632
[SDL][25.529] Scene objects count: 1
[SDL][25.529] Light re-definition: 140676445176840
[SDL][25.529] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][25.576] Configuration: 
[LuxCore][25.577]   path.pathdepth.total = 7
[LuxCore][25.577]   path.pathdepth.diffuse = 5
[LuxCore][25.577]   path.pathdepth.glossy = 5
[LuxCore][25.577]   path.pathdepth.specular = 6
[LuxCore][25.577]   path.hybridbackforward.enable = 0
[LuxCore][25.577]   path.hybridbackforward.partition = 0.80000000000000004
[LuxCore][25.577]   path.hybridbackforward.glossinessthreshold = 0.048999998718500137
[LuxCore][25.577]   film.noiseestimation.warmup = 8
[LuxCore][25.577]   film.noiseestimation.step = 32
[LuxCore][25.577]   sampler.sobol.adaptive.strength = 0.5
[LuxCore][25.577]   sampler.random.adaptive.strength = 0.5
[LuxCore][25.577]   sampler.metropolis.largesteprate = 0.40000000000000002
[LuxCore][25.577]   sampler.metropolis.maxconsecutivereject = 512
[LuxCore][25.577]   sampler.metropolis.imagemutationrate = 0.10000000000000001
[LuxCore][25.577]   renderengine.type = "PATHCPU"
[LuxCore][25.577]   sampler.type = "SOBOL"
[LuxCore][25.577]   film.width = 1920
[LuxCore][25.577]   film.height = 1080
[LuxCore][25.577]   film.filter.type = "BLACKMANHARRIS"
[LuxCore][25.577]   film.filter.width = 1.5
[LuxCore][25.577]   lightstrategy.type = "LOG_POWER"
[LuxCore][25.577]   scene.epsilon.min = 9.9999997473787516e-06
[LuxCore][25.577]   scene.epsilon.max = 0.10000000149011612
[LuxCore][25.577]   film.opencl.enable = 1
[LuxCore][25.577]   film.opencl.device = 0
[LuxCore][25.577]   path.forceblackbackground.enable = 0
[LuxCore][25.577]   renderengine.seed = 1
[LuxCore][25.577]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][25.577]   film.outputs.0.index = 0
[LuxCore][25.577]   film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
[LuxCore][25.577]   film.outputs.1.type = "RGB_IMAGEPIPELINE"
[LuxCore][25.577]   film.outputs.1.index = 1
[LuxCore][25.577]   film.outputs.1.filename = "RGB_IMAGEPIPELINE_1.png"
[LuxCore][25.577]   film.imagepipelines.1.0.type = "NOP"
[LuxCore][25.577]   film.imagepipelines.1.1.type = "TONEMAP_LINEAR"
[LuxCore][25.577]   film.imagepipelines.1.1.scale = 1
[LuxCore][25.577]   film.imagepipelines.1.radiancescales.0.enabled = 1
[LuxCore][25.577]   film.imagepipelines.1.radiancescales.0.globalscale = 1
[LuxCore][25.577]   film.imagepipelines.1.radiancescales.0.rgbscale = 1 1 1
[LuxCore][25.577]   film.imagepipelines.1.2.type = "GAMMA_CORRECTION"
[LuxCore][25.577]   film.imagepipelines.1.2.value = 2.2000000000000002
[LuxCore][25.577]   film.noiseestimation.index = 1
[LuxCore][25.577]   film.imagepipelines.0.0.type = "NOP"
[LuxCore][25.577]   film.imagepipelines.0.1.type = "TONEMAP_LINEAR"
[LuxCore][25.577]   film.imagepipelines.0.1.scale = 1
[LuxCore][25.577]   film.imagepipelines.0.radiancescales.0.enabled = 1
[LuxCore][25.577]   film.imagepipelines.0.radiancescales.0.globalscale = 1
[LuxCore][25.577]   film.imagepipelines.0.radiancescales.0.rgbscale = 1 1 1
[LuxCore][25.577]   batch.haltspp = 0
[LuxCore][25.577]   batch.halttime = 0
[LuxCore][25.577] File Name Resolver Configuration:
Export took 0.1 s
[LuxCore][25.578] Film resolution: 1920x1080
[SDL][25.578] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][25.578] Image pipeline: film.imagepipelines.0
[SDL][25.578] Image pipeline step 0: NOP
[SDL][25.578] Image pipeline step 1: TONEMAP_LINEAR
[SDL][25.578] Image pipeline: film.imagepipelines.1
[SDL][25.578] Image pipeline step 0: NOP
[SDL][25.578] Image pipeline step 1: TONEMAP_LINEAR
[SDL][25.579] Image pipeline step 2: GAMMA_CORRECTION
[SDL][25.579] Film output definition: RGB_IMAGEPIPELINE [RGB_IMAGEPIPELINE_0.png]
[SDL][25.579] Film output definition: RGB_IMAGEPIPELINE [RGB_IMAGEPIPELINE_1.png]
[LuxRays][25.593] OpenCL Platform 0: Advanced Micro Devices, Inc.
[LuxRays][25.593] Device 0 name: NativeThread
[LuxRays][25.593] Device 0 type: NATIVE_THREAD
[LuxRays][25.593] Device 0 compute units: 1
[LuxRays][25.593] Device 0 preferred float vector width: 4
[LuxRays][25.593] Device 0 max allocable memory: 0MBytes
[LuxRays][25.593] Device 0 max allocable memory block size: 0MBytes
[LuxRays][25.593] Device 1 name: gfx900
[LuxRays][25.593] Device 1 type: OPENCL_GPU
[LuxRays][25.593] Device 1 compute units: 56
[LuxRays][25.593] Device 1 preferred float vector width: 1
[LuxRays][25.593] Device 1 max allocable memory: 8176MBytes
[LuxRays][25.593] Device 1 max allocable memory block size: 4048MBytes
[LuxRays][25.593] Creating 8 intersection device(s)
[LuxRays][25.593] Allocating intersection device 0: NativeThread (Type = NATIVE_THREAD)
[LuxRays][25.593] Allocating intersection device 1: NativeThread (Type = NATIVE_THREAD)
[LuxRays][25.593] Allocating intersection device 2: NativeThread (Type = NATIVE_THREAD)
[LuxRays][25.593] Allocating intersection device 3: NativeThread (Type = NATIVE_THREAD)
[LuxRays][25.593] Allocating intersection device 4: NativeThread (Type = NATIVE_THREAD)
[LuxRays][25.594] Allocating intersection device 5: NativeThread (Type = NATIVE_THREAD)
[LuxRays][25.594] Allocating intersection device 6: NativeThread (Type = NATIVE_THREAD)
[LuxRays][25.594] Allocating intersection device 7: NativeThread (Type = NATIVE_THREAD)
[LuxCore][25.594] Configuring 8 CPU render threads
[LuxRays][25.594] Preprocessing DataSet
[LuxRays][25.594] Total vertex count: 36
[LuxRays][25.594] Total triangle count: 12
[LuxRays][25.594] Preprocessing DataSet done
[LuxRays][25.594] Adding DataSet accelerator: EMBREE
[LuxRays][25.594] Total vertex count: 36
[LuxRays][25.594] Total triangle count: 12
[LuxRays][25.595] EmbreeAccel build time: 0ms
Session started in 0.2 s
[LuxCore][25.775] Film OpenCL image pipeline
[LuxCore][25.775] Film OpenCL Device used: gfx900 Intersect
[LuxCore][25.775]   Device OpenCL version: OpenCL 2.0 AMD-APP (2906.7)
```

</p></details>

#### Short description of error

Blender UI becomes unresponsive right after the rendering process is initiated (either by switching the viewport to "Rendered" mode or by calling the "Render Image" command by F12). All 8 cores of CPU are occupied to 100% and nothing happens.

When switching viewport to "Rendering" mode there is a message in a left top corner which says: "Export Finished (0.0 s) | Creating RenderSession ..."

#### Exact steps for others to reproduce the error
1. Load the provided blend file (it's just a default cube with a matte material, a point light and a camera): [BlendLuxCore-2.3-beta3-problem.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4219938/BlendLuxCore-2.3-beta3-problem.blend.zip)
2. Start rendering.
3. Blender UI hangs and all CPU cores are loaded up to 100%.

Render engine is "Path" and device is "CPU".

#### Notes

Checked the same thing with Blender **v2.82 Alpha** (Build hash: b03066f7ee07) and it **works fine**.

**Comment by Theverat** [comment]
Can you still reproduce this? I have tested it on Windows and could not replicate the problem. Is it only happening on Linux?

**Comment by zezic** [comment]
Yes, I can reproduce it, it still hangs. OK, I'm going to check it on my Windows machine.

**Comment by zezic** [comment]
**UPDATE:** It **works** after cleaning my Blender configs. Sorry for taking your time. I will try to figure out the reason for such behavior. Thank you!

**Comment by Theverat** [comment]
Thanks for the quick response.
I tested it now on Linux as well (Ubuntu 18.04) and could again not find any problem, **however** since I have no OpenCL driver installed on this sytem, I could only test the build without OpenCL.

Does the problem happen on your end with the no-OpenCL build? It might be a driver issue.

(note that the rendered image will be fully white because the sky is too bright, a problem which was fixed after v2.3beta2 was released. You can set the sky gain to 0.00001 to make it darker).

**Comment by Theverat** [comment]
Good that you got it working, a bit unfortunate that we don't know the exact cause, but don't sweat it.

**Comment by zezic** [comment]
I kept my old Blender configs, so I can try to find the reason of that issue. I will report to this thread if there will be something.
_Too bad that Blender configuration is saved to the *.blend file which is hard to edit by hand._

**Comment by zezic** [comment]
I was wrong, generally it still hangs, but there is an interesting detail - it works when was just installed and enabled via add-ons tab without reopening the blend file. So:

1. Fresh Blender 2.82 config -> Install BlendLuxCore -> Switch engine to LuxCore -> Start render -> It works
2. Fresh Blender 2.82 config -> Install BlendLuxCore -> **Restart Blender or create new blend file from menu** -> Switch engine to LuxCore -> **It hangs**

**Comment by zezic** [comment]
Fixed by updating my amdgpu driver and installing OpenCL from amdgpu-pro-19.50 package. It came out that Cycles OpenCL rendering is also was broken by the way.
